#!/bin/sh
#set -eo pipefail

events="/sys/kernel/debug/tracing/events"
uprobe_base="/sys/kernel/debug/tracing"
uprobe_events="${uprobe_base}/uprobe_events"
exe=""
args=""
func=""
rfunc=""
tmp_probes=/tmp/tmp_probes
tmp_rprobes=/tmp/tmp_rprobes
probes=/tmp/probes
rprobes=/tmp/rprobes
#probe_name=""
#rprobe_name=""
#probe=""
#rprobe=""

#probe_path=""

#rprobe_name=""
#rprobe_path=""
#func_name=""

show_help()
{
  printf "Usage: %s exec [func] [probe] [-e|--enable] [-p pid]\n" ${0}
  printf "\nArgs:\n"
  printf "\texec(required): the executable\n"
  printf "\tfunc(optional): if added list the with lineno and args\n"
  printf "\tprobe(optional): if added generate the ftrace probe (put between quotes as different args expressed separated by spaces)\n"
  printf "\t-e(optional): enable the live tracer\n"
  printf "\t-p(optional): pid filter (-p pid)\n"
  printf "\n"
}

show_arg_help()
{
  printf "Usage: $0 ${action} [<ARGS>]\n\n"
  printf "args:\n\n"
  
  while [[ $# > 0 ]]; do
    printf "\t${1}\n\n"
    shift
  done
}

handler_int() {
  probe_ops "disable"
  probe_ops "unregister"

  if [ -f ${tmp_probes} ]; then
    rm -f ${tmp_probes}
  fi
  if [ -f ${tmp_rprobes} ]; then
    rm -f ${tmp_rprobes}
  fi
  exit 1
}
trap 'handler_int ${probe_name}' SIGINT

disable_probe()
{
  echo 0 > $probe_path
  printf "Probe %s is disabled successfully\n" $probe_path
}

get_func_name()
{
  local probe_type=$1
  local probe=$2

  echo $probe | grep "${probe_type}" | awk -F' ' '{ print $1 }' | awk -F'/' '{ print $2 }'
}

get_probe_name()
{
  local probe_type=$1
  local probe=$2

  echo $probe | grep ${probe_type} | awk -F' ' '{ print $1 }' | awk -F'/' '{ print $1 }' | awk -F':' '{ print $2 }'
}

get_probe_path()
{
  local probe_name=$1

  echo "${uprobe_base}/events/${probe_name}/enable"
}

enable_probe()
{
  probe_ops "enable"
  printf "Probe %s is enabled successfully\n" $probe_path
}

set_pid_filter()
{
  local pid=$1
  local probe=$2
  local probe_type=$3
  local probe_name=$(get_probe_name ${probe_type} $probe)
  local probe_path=$(get_probe_path ${probe_name})
  local filter_path="${uprobe_base}/events/${probe_name}/${func}/filter"
  local rfilter_path="${uprobe_base}/events/${probe_name}/${rfunc}/filter"

  if [ -z $pid ]; then
    printf "No pid is submitted for filtering, pid: %d\n" $pid 
  else
    printf "Filtering for pid: %d\n" $pid 
    echo "common_pid == $pid" > ${filter_path} && echo "common_pid == $pid" > ${rfilter_path}
  fi
}

live_probe()
{
  local pid=$1

  write_probes_files
  probe_ops "register"

  if [ ! -z "${pid}" ]; then
    probe_ops "filter" $pid
  fi
  enable_probe
  printf "\n\nTracing $probe, press ctrl + c to cancel..\n\n"
  cat ${uprobe_base}/trace_pipe 
}

write_probes_files()
{
  > ${probes}
  > ${rprobes}
  perf probe -x $exe --dry-run -D "${func} $args" > ${tmp_probes}
  local i=0
  cat ${tmp_probes} | while read line; do
    echo "$line" | sed -e "s/${func}[^ ]* /${func}${i} /" >> /tmp/probes
    i=$(expr $i + 1)
  done
  perf probe -x $exe --dry-run -D "${func}%return \$retval" > ${tmp_rprobes}
  local i=0
  cat ${tmp_rprobes} | while read line; do
    echo $line | sed -e "s/${func}[^ ]* /${func}_return${i} /" >> /tmp/rprobes
    i=$(expr $i + 1)
  done
}

probe_ops()
{
  local opt=$1

  if [[ ${opt} == "register" ]]; then
    cat ${probes} | while read line; do
      echo "$line" >> $uprobe_events
    done
    cat ${rprobes} | while read line; do
      echo "$line" >> $uprobe_events
    done
  elif [[ ${opt} == "unregister" ]]; then
    cat ${probes} | while read line; do
      local revoked_probe=$(echo "'$line'" | awk -F' ' '{ print $1 }' | awk -F':' '{ print $2 }')
      echo "-:${revoked_probe}" >> $uprobe_events
    done
    cat ${rprobes} | while read line; do
      local revoked_probe=$(echo "'$line'" | awk -F' ' '{ print $1 }' | awk -F':' '{ print $2 }')
      echo "-:${revoked_probe}" >> $uprobe_events
    done
  elif [[ ${opt} == "show" ]]; then
    cat ${probes} | while read line; do
      echo "'$line'"
    done
    cat ${rprobes} | while read line; do
      echo "'$line'"
    done
  elif [[ ${opt} == "enable" ]]; then
    cat ${probes} | awk -F' ' '{ print $1 }' | awk -F':' '{ print $2 }' | while read line; do
      echo 1 > ${events}/${line}/enable
    done
    i=0
    cat ${rprobes} | awk -F' ' '{ print $1 }' | awk -F':' '{ print $2 }' | while read line; do
      echo 1 > ${events}/${line}/enable
    done
  elif [[ ${opt} == "disable" ]]; then
    cat ${probes} | awk -F' ' '{ print $1 }' | awk -F':' '{ print $2 }' | while read line; do
      echo 0 > ${events}/${line}/enable
    done
    i=0
    cat ${rprobes} | awk -F' ' '{ print $1 }' | awk -F':' '{ print $2 }' | while read line; do
      echo 0 > ${events}/${line}/enable
    done
  elif [[ ${opt} == "filter" ]]; then
    local pid=$2
    cat ${probes} | awk -F' ' '{ print $1 }' | awk -F':' '{ print $2 }' | while read line; do
      echo "common_pid == $pid" > ${events}/${line}/filter
    done
    i=0
    cat ${rprobes} | awk -F' ' '{ print $1 }' | awk -F':' '{ print $2 }' | while read line; do
      echo "common_pid == $pid" > ${events}/${line}/filter
    done
  else
    printf "probe_ops: Unknown option\n"
    exit 1
  fi
}

gen_probe()
{
  local args=$1

  write_probes_files
  probe_ops "show"
}

list_exec_funcs()
{
  printf "\nAvailable function:\n\n"
  perf probe -x $exe -F
  printf "\n"
}

list_func_lines()
{
  local func_name=$(echo $func | awk -F':' '{ print $1 }')
  local func_idx=$(echo $func | awk -F':' '{ print $2 }')

  perf probe -x ${exe} --dry-run --line "${func_name}"
}

is_file_exist()
{
  if [ ! -e $exe ]; then
    printf "Unable to find the executable %s\n" $1
    show_help
    exit 1
  fi
}

is_func_exist()
{
  local func_name=$(echo $func | awk -F':' '{ print $1 }')
  local func_idx=$(echo $func | awk -F':' '{ print $2 }')

  list_exec_funcs $exe | grep -w $func_name
  if [[ $? != 0 ]]; then
    printf "Unable to find the function %s in the executable %s\n" $func_name $exe
    show_help
    exit 1
  fi
}


##################### main #####################

if [[ $# == 0 ]]; then
  show_help
  exit 1
fi

choice=$#

case "$choice" in
    1)
	exe=$1
	is_file_exist
	list_exec_funcs
        ;;
    2)
	exe=$1
	is_file_exist
	shift
	func=$1
	if [[ "$func" =~ ^(-h|--help)$ ]]; then
	  show_arg_help "func(optional): if added list the with lineno and args"
	  exit 1
	fi

	is_func_exist
	list_func_lines
        ;;
    3)
	exe=$1
	is_file_exist
	shift
	func=$1
	if [[ "$func" =~ ^(-h|--help)$ ]]; then
	  show_arg_help "func(optional): if added list the with lineno and args"
	  exit 1
	fi
	is_func_exist
	shift
	args=$1

        gen_probe "${args}"
  	printf "\nYou need to register your probe in %s, live trace on %s, and later you need to deregister manually too\n" ${uprobe_events} "${uprobe_base}/trace_pipe"
        ;;
    4)
        exe=$1
        is_file_exist
        shift
        func=$1
        if [[ "$func" =~ ^(-h|--help)$ ]]; then
          show_arg_help "func(optional): if added list the with lineno and args"
          exit 1
        fi
        is_func_exist
        shift
        args=$1
        shift
        opt=$1
        if [[ "$opt" != "-e" ]]; then
          show_arg_help "-e(optional): enable the live tracer"
          exit 1
        fi

        live_probe
        ;;
    5)
        exe=$1
        is_file_exist
        shift
        func=$1
        if [[ "$func" =~ ^(-h|--help)$ ]]; then
          show_arg_help "func(optional): if added list the with lineno and args"
          exit 1
        fi
        is_func_exist
        shift
        args=$1
        shift
        opt1=$1
        shift
        opt2=$1
        if [[ "$opt1" == "-e" ]]; then
	  show_arg_help "-p(optional): pid filter (-p pid)"
  	else
	  printf "Unknown options: %s\n" ${opt1}
	  show_arg_help "-e(optional): enable the live tracer" "-p(optional): pid filter (-p pid)"
        fi
        ;;
    6)
        exe=$1
        is_file_exist
        shift
        func=$1
        if [[ "$func" =~ ^(-h|--help)$ ]]; then
          show_arg_help "func(optional): if added list the with lineno and args"
          exit 1
        fi
        is_func_exist
        shift
        args=$1
        shift
        opt1=$1
        shift
        opt2=$1
        shift
        pid=$1
        if [[ "$opt1" != "-e" && "$opt2" != "-p" ]]; then
	  show_arg_help "-e(optional): enable the live tracer" "-p(optional): pid filter(-p pid)"
          exit 1
        fi

        live_probe $pid
        ;;
    *)
        echo "Error: Invalid selection. Please choose a number between 1 and 4."
        exit 1
        ;;
esac

