#!/bin/sh
#set -eo pipefail

uprobe_base="/sys/kernel/debug/tracing"
uprobe_events="${uprobe_base}/uprobe_events"
probe=""
probe_name=""
probe_path=""
func_name=""

show_help()
{
  printf "Usage: %s exec [func] [probe] [-e|--enable] [-p pid]\n" ${0}
  printf "\nArgs:\n"
  printf "\texec(required): the executable\n"
  printf "\tfunc(optional): if added list the with lineno and args\n"
  printf "\tprobe(optional): if added generate the ftrace probe (put between quotes as different args expressed separated by spaces)\n"
  printf "\t-e(optional): enable the live tracer\n"
  printf "\t-p(optional): pid filter (-p pid)\n"
  printf "\n"
}

show_arg_help()
{
  printf "Usage: $0 ${action} [<ARGS>]\n\n"
  printf "args:\n\n"
  
  while [[ $# > 0 ]]; do
    printf "\t${1}\n\n"
    shift
  done
}

handler_int() {
  disable_probe 
  unregister_probe
  exit 1
}
trap 'handler_int ${probe_name}' SIGINT

disable_probe()
{
  echo 0 > $probe_path
  printf "Probe %s is disabled successfully\n" $probe_path
}

unregister_probe()
{
  local probe_unreg_expres="-:${probe_name}/${func}"
  echo "${probe_unreg_expres}" >> ${uprobe_events} >> ${uprobe_events}
  #echo "-:probe_main/take_string" >> /sys/kernel/debug/tracing/uprobe_events
  if [[ $? == 0 ]]; then
    printf "Probe %s is unregistered successfully\n" ${probe}
  else
    printf "Probe %s unregisteration is unsuccessful\n" "${probe}"
  fi
}

get_probe_path()
{
  local probe_name=$1

  echo "${uprobe_base}/events/${probe_name}/enable"
}

enable_probe()
{
  local probe=$1
  probe_path=$(get_probe_path ${probe_name})

  echo 1 > $probe_path
  printf "Probe %s is enabled successfully\n" $probe_path
}

set_pid_filter()
{
  local pid=$1
  local probe=$2
  local func=$3
  local probe_name=$(echo $probe | awk -F' ' '{print $1}' | awk -F'/' '{ print $1 }' | awk -F':' '{print $2}')
  local probe_path=$(get_probe_path ${probe_name})
  local filter_path="${uprobe_base}/events/${probe_name}/${func}/filter"

  if [ -z $pid ]; then
    printf "No pid is submitted for filtering, pid: %d\n" $pid 
  else
    printf "Filtering for pid: %d\n" $pid 
    echo "common_pid == $pid" > ${filter_path}
  fi
}

register_probe()
{
  local probe=$1

  if [ -f "${uprobe_base}/events/${probe_name}/enable" ]; then
    echo 0 > ${uprobe_base}/events/${probe_name}/enable
  fi

  echo $probe > ${uprobe_events}
  if [[ $? == 0 ]]; then
    printf "Probe %s is registered successfully\n" ${probe}
  else
    printf "Probe %s registeration is unsuccessful, probe: %s, uprobe_events: %s\n" "${probe}" ${uprobe_events}
    exit 1
  fi
}

live_probe()
{
  local exe=$1
  func=$2
  local args=$3
  local pid=$4
  local lines=$(gen_probe $exe $func $args | wc -l)
  if [[ $lines > 3 ]]; then
    printf "You have more than one probe options, pick the one you prefer\n"
    gen_probe $exe $func "$args"
    exit 1
  fi

  probe=$(gen_probe $exe $func "$args" 2>/dev/null | grep 'p:probe')
  probe_name=$(echo $probe | awk -F' ' '{print $1}' | awk -F'/' '{ print $1 }' | awk -F':' '{print $2}')

  register_probe "$probe"
  if [ ! -z "${pid}" ]; then
    set_pid_filter $pid "$probe" $func
  fi
  enable_probe "$probe"
  printf "\n\nTracing $probe, press ctrl + c to cancel..\n\n"
  cat ${uprobe_base}/trace_pipe 
}

gen_probe()
{
  local exe=$1
  func=$2
  local args=$3

  perf probe -x $exe --dry-run -D "$func $args"
  printf "\nYou need to register your probe in %s, live trace on %s, and later you need to deregister manually too\n" ${uprobe_events} "${uprobe_base}/trace_pipe"
}

list_exec_funcs()
{
  local exe=$1

  printf "\nAvailable function:\n\n"
  perf probe -x $exe -F
  printf "\n"
}

list_func_lines()
{
  local exe=$1
  func=$2
  local func_name=$(echo $func | awk -F':' '{ print $1 }')
  local func_idx=$(echo $func | awk -F':' '{ print $2 }')

  perf probe -x ${exe} --dry-run --line "${func_name}"
}

is_file_exist()
{
  local exe=$1

  if [ ! -e $exe ]; then
    printf "Unable to find the executable %s\n" $1
    show_help
    exit 1
  fi
}

is_func_exist()
{
  local exe=$1
  local func=$2
  local func_name=$(echo $func | awk -F':' '{ print $1 }')
  local func_idx=$(echo $func | awk -F':' '{ print $2 }')

  list_exec_funcs $exe | grep $func_name
  if [[ $? != 0 ]]; then
    printf "Unable to find the function %s in the executable %s\n" $func_name $exe
    show_help
    exit 1
  fi
}


##################### main #####################

if [[ $# == 0 ]]; then
  show_help
  exit 1
fi

choice=$#

case "$choice" in
    1)
	exe=$1
	is_file_exist $exe

	list_exec_funcs $exe
        ;;
    2)
	exe=$1
	is_file_exist $exe
	shift
	func=$1
	if [[ "$func" =~ ^(-h|--help)$ ]]; then
	  show_arg_help "func(optional): if added list the with lineno and args"
	  exit 1
	fi
	is_func_exist $exe $func

	list_func_lines $exe $func
        ;;
    3)
	exe=$1
	is_file_exist $exe
	shift
	func=$1
	if [[ "$func" =~ ^(-h|--help)$ ]]; then
	  show_arg_help "func(optional): if added list the with lineno and args"
	  exit 1
	fi
	is_func_exist $exe $func
	shift
	args=$1

        gen_probe $exe $func "$args"
        ;;
    4)
        exe=$1
        is_file_exist $exe
        shift
        func=$1
        if [[ "$func" =~ ^(-h|--help)$ ]]; then
          show_arg_help "func(optional): if added list the with lineno and args"
          exit 1
        fi
        is_func_exist $exe $func
        shift
        args=$1
        shift
        opt=$1
        if [[ "$opt" != "-e" ]]; then
          show_arg_help "-e(optional): enable the live tracer"
          exit 1
        fi

        live_probe $exe $func "$args"
        ;;
    5)
        exe=$1
        is_file_exist $exe
        shift
        func=$1
        if [[ "$func" =~ ^(-h|--help)$ ]]; then
          show_arg_help "func(optional): if added list the with lineno and args"
          exit 1
        fi
        is_func_exist $exe $func
        shift
        args=$1
        shift
        opt1=$1
        shift
        opt2=$1
        if [[ "$opt1" == "-e" ]]; then
	  show_arg_help "-p(optional): pid filter (-p pid)"
  	else
	  printf "Unknown options: %s\n" ${opt1}
	  show_arg_help "-e(optional): enable the live tracer" "-p(optional): pid filter (-p pid)"
        fi
        ;;
    6)
        exe=$1
        is_file_exist $exe
        shift
        func=$1
        if [[ "$func" =~ ^(-h|--help)$ ]]; then
          show_arg_help "func(optional): if added list the with lineno and args"
          exit 1
        fi
        is_func_exist $exe $func
        shift
        args=$1
        shift
        opt1=$1
        shift
        shift
        opt2=$1
        if [[ "$opt1" != "-e" && "$opt2" != "-p" ]]; then
	  show_arg_help "-e(optional): enable the live tracer" "-p(optional): pid filter(-p pid)"
          exit 1
        fi

        live_probe $exe $func "$args" $opt2
        ;;
    *)
        echo "Error: Invalid selection. Please choose a number between 1 and 4."
        exit 1
        ;;
esac

